"""Public façade for bounded semantic-shape duplicate primitives."""

from ici.engines._python_dup_semantics import (
    MAX_PYTHON_SEMANTIC_FILES,
    MAX_PYTHON_SEMANTIC_NODES,
    MAX_PYTHON_SEMANTIC_REGIONS,
    MAX_PYTHON_SEMANTIC_SERIALIZED_CHARS,
    MAX_SEMANTIC_FILES,
    MAX_SEMANTIC_NODES,
    MAX_SEMANTIC_REGIONS,
    MAX_SEMANTIC_SERIALIZED_CHARS,
    SEMANTIC_SHAPE_ALGORITHM,
    SEMANTIC_SHAPE_VERSION,
    SemanticAnalysisOutcome,
    SemanticExclusion,
    SemanticLimits,
    SemanticOutcome,
    SemanticRegion,
    analyze_python_semantic_source,
    analyze_python_semantic_sources,
    analyze_python_source,
    analyze_python_sources,
    canonical_python_shape,
    extract_python_semantic_regions,
    python_semantic_regions,
    semantic_shape_fingerprint,
)

__all__ = [
    "MAX_PYTHON_SEMANTIC_FILES",
    "MAX_PYTHON_SEMANTIC_NODES",
    "MAX_PYTHON_SEMANTIC_REGIONS",
    "MAX_PYTHON_SEMANTIC_SERIALIZED_CHARS",
    "MAX_SEMANTIC_FILES",
    "MAX_SEMANTIC_NODES",
    "MAX_SEMANTIC_REGIONS",
    "MAX_SEMANTIC_SERIALIZED_CHARS",
    "SEMANTIC_SHAPE_ALGORITHM",
    "SEMANTIC_SHAPE_VERSION",
    "SemanticAnalysisOutcome",
    "SemanticExclusion",
    "SemanticLimits",
    "SemanticOutcome",
    "SemanticRegion",
    "analyze_python_semantic_source",
    "analyze_python_semantic_sources",
    "analyze_python_source",
    "analyze_python_sources",
    "canonical_python_shape",
    "extract_python_semantic_regions",
    "python_semantic_regions",
    "semantic_shape_fingerprint",
]
