"""Positive compiler-option policy for read-only C/C++ analysis replay."""

from __future__ import annotations

import re

COMPILER_CAPABILITIES = ("gcc", "g++", "clang", "clang++")
COMPILER_NAME_RE = re.compile(
    r"^(?:(?:[A-Za-z0-9_+.]+-)+)?(?:gcc|g\+\+|clang|clang\+\+|cc|c\+\+)"
    r"(?:-[0-9][A-Za-z0-9_.-]*)?(?:\.exe)?$",
    re.IGNORECASE,
)
DROP_EXACT = frozenset(
    {
        "-c",
        "-S",
        "-E",
        "-fsyntax-only",
        "-M",
        "-MM",
        "-MD",
        "-MMD",
        "-MP",
        "-MG",
        "-H",
        "-save-temps",
        "--save-temps",
        "-ftime-trace",
        "-ftime-report",
        "-ftime-report-details",
        "-fmem-report",
        "-fstats",
        "-pipe",
        "-fcolor-diagnostics",
        "-fno-color-diagnostics",
        "-v",
        "--verbose",
    }
)
DROP_VALUE = frozenset(
    {
        "-o",
        "--output",
        "-MF",
        "-MT",
        "-MQ",
        "-MJ",
        "-dumpdir",
        "-dumpbase",
        "-dumpbase-ext",
        "-auxbase",
        "-auxbase-strip",
        "-serialize-diagnostics",
        "--serialize-diagnostics",
        "-dependency-file",
        "--dependency-file",
        "-fdiagnostics-serialized-file",
    }
)
DROP_JOINED = (
    "-o",
    "--output=",
    "-MF",
    "-MT",
    "-MQ",
    "-MJ",
    "-Wp,-M",
    "-save-temps=",
    "--save-temps=",
    "-ftime-trace=",
    "-fdiagnostics-color=",
    "-fdiagnostics-format=",
    "-dependency-file=",
    "--dependency-file=",
    "-fdiagnostics-serialized-file=",
)
DROP_PREFIXES = ("-g",)
PRESERVE_VALUE = frozenset(
    {
        "-D",
        "-U",
        "-I",
        "-F",
        "-x",
        "--language",
        "-std",
        "-include",
        "-include-pch",
        "-imacros",
        "-isystem",
        "-iquote",
        "-idirafter",
        "-iprefix",
        "-iwithprefix",
        "-iwithprefixbefore",
        "-iframework",
        "-iframeworkwithsysroot",
        "-isysroot",
        "--sysroot",
        "-target",
        "--target",
        "-arch",
        "-march",
        "-mcpu",
        "-mtune",
        "-mabi",
        "-resource-dir",
    }
)
REJECT_EXACT = frozenset(
    {
        "-Xclang",
        "-Xpreprocessor",
        "-Xassembler",
        "-Xlinker",
        "-mllvm",
        "-load",
        "-load-plugin",
        "-plugin",
        "-plugin-arg",
        "-cc1",
        "-cc1as",
        "-wrapper",
        "--config",
        "--config-system-dir",
        "--config-user-dir",
        "-B",
        "-specs",
    }
)
REJECT_PREFIXES = (
    "-Xclang=",
    "-Xpreprocessor=",
    "-Xassembler=",
    "-Xlinker=",
    "-mllvm=",
    "-mmlir",
    "-Wa,",
    "-Wl,",
    "-Wp,",
    "-fplugin",
    "-fpass-plugin",
    "-fmodules",
    "-fmodule-",
    "-fcxx-modules",
    "-fprebuilt-module-path",
    "-fdump-",
    "-fopt-info",
    "-fstack-usage",
    "-fcallgraph-info",
    "-fprofile-generate",
    "-fprofile-dir",
    "-fprofile-note",
    "-fprofile-arcs",
    "-ftest-coverage",
    "-fpath-coverage",
    "-fdiagnostics-add-output",
    "-fdiagnostics-set-output",
    "-fsave-optimization-record",
    "-foptimization-record-file",
    "-fproc-stat-report",
    "-fmemory-profile",
    "-freport-bug",
    "-fself-test",
    "-iplugindir",
    "-emit-",
    "--precompile",
    "-precompile",
    "-save-stats",
    "--save-stats",
    "-stats-file",
    "-time=",
    "-aux-info",
    "--symbol-graph-dir",
    "-plugin-arg-",
    "-wrapper=",
    "-specs=",
    "--specs",
    "--config=",
    "--config-system-dir=",
    "--config-user-dir=",
    "--gcc-toolchain",
    "--prefix",
    "-working-directory",
    "--vfsoverlay",
    "-vfsoverlay",
    "--for-assembler",
    "--for-linker",
    "--for-preprocessor",
    "--coverage",
    "-coverage",
    "--profile",
    "-pg",
    "-B",
)
SAFE_EXACT = frozenset(
    {
        "-ansi",
        "-pedantic",
        "-pedantic-errors",
        "--pedantic-errors",
        "-pthread",
        "-nostdinc",
        "-nostdinc++",
        "-undef",
        "-trigraphs",
        "-Qunused-arguments",
        "-fPIC",
        "-fPIE",
        "-fpic",
        "-fpie",
        "-fexceptions",
        "-fno-exceptions",
        "-frtti",
        "-fno-rtti",
        "-fpermissive",
        "-ffreestanding",
        "-fhosted",
        "-fshort-enums",
        "-fshort-wchar",
        "-fsigned-char",
        "-funsigned-char",
        "-fsized-deallocation",
        "-fno-sized-deallocation",
        "-fthreadsafe-statics",
        "-fno-threadsafe-statics",
        "-fvisibility-inlines-hidden",
        "-fno-visibility-inlines-hidden",
        "-fconcepts",
        "-fconcepts-ts",
        "-fcoroutines",
        "-fcoroutines-ts",
        "-fdelayed-template-parsing",
        "-fchar8_t",
        "-fno-char8_t",
        "-fms-extensions",
        "-fms-compatibility",
        "-fno-access-control",
        "-fno-elide-constructors",
        "-fno-enforce-eh-specs",
        "-fno-operator-names",
        "-fno-optional-diags",
        "-fno-use-cxa-atexit",
        "-fno-weak",
        "-fstrict-enums",
        "-fgnu-keywords",
        "-fno-gnu-keywords",
        "-fimplicit-templates",
        "-fno-implicit-templates",
        "-fopenmp",
        "-fno-openmp",
        "-fomit-frame-pointer",
        "-fno-omit-frame-pointer",
        "-fstrict-aliasing",
        "-fno-strict-aliasing",
        "-fcommon",
        "-fno-common",
        "-fbuiltin",
        "-fno-builtin",
    }
)
SAFE_PREFIXES = (
    "-D",
    "-U",
    "-I",
    "-F",
    "-W",
    "-std=",
    "--std=",
    "-isystem",
    "-iquote",
    "-idirafter",
    "-iprefix",
    "-iwithprefix",
    "-iframework",
    "-imacros",
    "--sysroot=",
    "-isysroot=",
    "-target=",
    "--target=",
    "-arch=",
    "-resource-dir=",
    "-stdlib=",
    "-rtlib=",
    "-unwindlib=",
    "-fabi-version=",
    "-fabi-compat-version=",
    "-faligned-new=",
    "-fconstexpr-depth=",
    "-fconstexpr-loop-limit=",
    "-fconstexpr-ops-limit=",
    "-fconstexpr-steps=",
    "-fmacro-prefix-map=",
    "-ffile-prefix-map=",
    "-fdebug-prefix-map=",
    "-fms-compatibility-version=",
    "-fno-builtin-",
    "-fopenmp-version=",
    "-fpack-struct=",
    "-fsanitize=",
    "-fno-sanitize=",
    "-fsanitize-recover=",
    "-fno-sanitize-recover=",
    "-ftemplate-backtrace-limit=",
    "-ftemplate-depth=",
    "-fvisibility=",
)
SAFE_LANGUAGE_VALUES = frozenset({"c", "c++"})
_OPTIMIZATION_RE = re.compile(r"^-O(?:[0-3sgz]|fast)?$")


def should_drop(token: str) -> bool:
    return (
        token in DROP_EXACT
        or any(token.startswith(prefix) and token != prefix for prefix in DROP_JOINED)
        or any(token.startswith(prefix) for prefix in DROP_PREFIXES)
    )


def is_rejected(token: str) -> bool:
    return token in REJECT_EXACT or any(token.startswith(prefix) for prefix in REJECT_PREFIXES)


def is_safe(token: str) -> bool:
    if token in SAFE_EXACT or _OPTIMIZATION_RE.fullmatch(token) is not None:
        return True
    if token.startswith("-m") and len(token) > 2:
        return True
    if token in {"-xc", "-xc++"}:
        return True
    if token.startswith("--language="):
        return token.removeprefix("--language=") in SAFE_LANGUAGE_VALUES
    return any(token.startswith(prefix) and token != prefix for prefix in SAFE_PREFIXES)
